### Show current cart
##
curl --request GET \
     --url {{url}}/cart \
     --header 'accept: application/json'

### Register cart adding a item
##
curl --request POST \
     --url {{url}}/cart \
     --header 'accept: application/json' \
     --data product_id=2 \
     --data quantity=2

### Add product to cart
##
curl --request POST \
     --url {{url}}/cart/add_item \
     --header 'accept: application/json' \
     --data product_id=2 \
     --data quantity=2


### List products
##
curl --request GET \
     --url {{url}}/products
